# Site settings
title: Random Stuff About Stuff
email: david.kerwick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  General things I come across that may be useful for other people and so I can find it again as well.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  david-kerwick
future: true
# Build settings
markdown: kramdown
